package com.dirzaaulia.countries.ui.mars

import com.dirzaaulia.countries.domain.mars.MarsLandmark

val MARS_LANDMARKS =
    listOf(
        // Rovers & Landers
        MarsLandmark(
            id = "perseverance",
            name = "Perseverance & Ingenuity",
            subtitle = "Jezero Crater",
            category = "ROVER",
            lat = 18.38,
            lng = 77.58,
            year = 2021,
            agency = "NASA",
            elevationKm = -2.5,
            significance = "Seeking signs of ancient life and collecting samples of rock and regolith.",
        ),
        MarsLandmark(
            id = "curiosity",
            name = "Curiosity",
            subtitle = "Gale Crater",
            category = "ROVER",
            lat = -4.58,
            lng = 137.44,
            year = 2012,
            agency = "NASA",
            elevationKm = -4.5,
            significance = "Determining if Mars ever had an environment capable of supporting microbial life.",
        ),
        MarsLandmark(
            id = "zhurong",
            name = "Zhurong",
            subtitle = "Utopia Planitia",
            category = "ROVER",
            lat = 25.07,
            lng = 109.93,
            year = 2021,
            agency = "CNSA",
            elevationKm = -4.1,
            significance = "Part of Tianwen-1, explored surface composition and looked for water ice.",
        ),
        MarsLandmark(
            id = "insight",
            name = "InSight",
            subtitle = "Elysium Planitia",
            category = "LANDER",
            lat = 4.50,
            lng = 135.62,
            year = 2018,
            agency = "NASA",
            elevationKm = -2.6,
            significance = "Studied the deep interior of Mars, measuring marsquakes.",
        ),
        MarsLandmark(
            id = "opportunity",
            name = "Opportunity",
            subtitle = "Meridiani Planum",
            category = "ROVER",
            lat = -1.95,
            lng = 354.47,
            year = 2004,
            agency = "NASA",
            elevationKm = -1.4,
            significance = "Discovered evidence of past water activity. Operated for over 14 years.",
        ),
        MarsLandmark(
            id = "spirit",
            name = "Spirit",
            subtitle = "Gusev Crater",
            category = "ROVER",
            lat = -14.57,
            lng = 175.47,
            year = 2004,
            agency = "NASA",
            elevationKm = -1.9,
            significance = "Explored the Columbia Hills and found evidence of ancient hot springs.",
        ),
        MarsLandmark(
            id = "pathfinder",
            name = "Pathfinder & Sojourner",
            subtitle = "Ares Vallis",
            category = "ROVER",
            lat = 19.33,
            lng = 326.45,
            year = 1997,
            agency = "NASA",
            elevationKm = -3.7,
            significance = "First successful rover on Mars.",
        ),
        MarsLandmark(
            id = "viking-1",
            name = "Viking 1",
            subtitle = "Chryse Planitia",
            category = "LANDER",
            lat = 22.48,
            lng = 312.03, // 47.97 W
            year = 1976,
            agency = "NASA",
            elevationKm = -3.6,
            significance = "First spacecraft to successfully land on Mars and perform its mission.",
        ),
        MarsLandmark(
            id = "viking-2",
            name = "Viking 2",
            subtitle = "Utopia Planitia",
            category = "LANDER",
            lat = 47.97,
            lng = 134.3, // 225.7 W -> 360 - 225.7 = 134.3 E
            year = 1976,
            agency = "NASA",
            elevationKm = -4.2,
            significance = "Operated on the surface for 1,316 days, searching for life.",
        ),
        // Geological Record Holders
        MarsLandmark(
            id = "olympus_mons",
            name = "Olympus Mons",
            subtitle = "Tallest Volcano",
            category = "MOUNTAIN",
            lat = 18.65,
            lng = 226.2,
            year = null,
            agency = null,
            elevationKm = 21.9,
            significance = "The tallest volcano and highest known mountain in the solar system.",
        ),
        MarsLandmark(
            id = "valles_marineris",
            name = "Valles Marineris",
            subtitle = "Grandest Canyon",
            category = "CANYON",
            lat = -14.0,
            lng = 301.0,
            year = null,
            agency = null,
            elevationKm = -8.0,
            significance = "A massive canyon system that runs 4,000 km along the Martian equator.",
        ),
        MarsLandmark(
            id = "hellas_planitia",
            name = "Hellas Planitia",
            subtitle = "Deepest Impact Basin",
            category = "BASIN",
            lat = -42.4,
            lng = 70.5,
            year = null,
            agency = null,
            elevationKm = -7.1,
            significance = "The largest visible impact crater on Mars and the lowest point on the surface.",
        ),
        MarsLandmark(
            id = "planum_boreum",
            name = "Planum Boreum",
            subtitle = "North Polar Ice Cap",
            category = "POLAR_CAP",
            lat = 85.0,
            lng = 0.0,
            year = null,
            agency = null,
            elevationKm = 2.0,
            significance = "Permanent ice cap consisting mostly of water ice and carbon dioxide.",
        ),
        MarsLandmark(
            id = "planum_australe",
            name = "Planum Australe",
            subtitle = "South Polar Ice Cap",
            category = "POLAR_CAP",
            lat = -85.0,
            lng = 0.0,
            year = null,
            agency = null,
            elevationKm = 3.0,
            significance = "Permanent southern ice cap, notably colder and with more frozen CO2 than the north.",
        ),
    )
