package com.dirzaaulia.countries.domain.moon

val LUNAR_HERITAGE_MISSIONS: List<LunarLandmark> =
    listOf(
        // Apollo Crewed Missions (NASA)
        LunarLandmark(
            id = "apollo-11",
            name = "Apollo 11",
            latinName = "Statio Tranquillitatis",
            type = LunarLandmarkType.CREWED_APOLLO,
            lat = 0.67408,
            lng = 23.47297,
            mission = LunarMissionMetadata("NASA", "US", "1969-07-20", 21.55, null),
            significance = "First human Moon landing. Neil Armstrong and Buzz Aldrin spent 21.5 hours on the lunar surface.",
        ),
        LunarLandmark(
            id = "apollo-12",
            name = "Apollo 12",
            latinName = "Oceanus Procellarum",
            type = LunarLandmarkType.CREWED_APOLLO,
            lat = -3.01239,
            lng = -23.42157,
            mission = LunarMissionMetadata("NASA", "US", "1969-11-19", 34.30, null),
            significance = "Pinpoint landing within walking distance (180m) of the uncrewed Surveyor 3 probe.",
        ),
        LunarLandmark(
            id = "apollo-14",
            name = "Apollo 14",
            latinName = "Fra Mauro Highlands",
            type = LunarLandmarkType.CREWED_APOLLO,
            lat = -3.64530,
            lng = -17.47136,
            mission = LunarMissionMetadata("NASA", "US", "1971-02-05", 42.28, null),
            significance = "Explored Cone crater ejecta blanket; Alan Shepard hit two golf balls on the lunar surface.",
        ),
        LunarLandmark(
            id = "apollo-15",
            name = "Apollo 15",
            latinName = "Hadley-Apennine",
            type = LunarLandmarkType.CREWED_APOLLO,
            lat = 26.13222,
            lng = 3.63386,
            mission = LunarMissionMetadata("NASA", "US", "1971-07-30", 77.31, "LRV-001"),
            significance = "First J-series extended stay mission utilizing the Lunar Roving Vehicle near Hadley Rille.",
        ),
        LunarLandmark(
            id = "apollo-16",
            name = "Apollo 16",
            latinName = "Descartes Highlands",
            type = LunarLandmarkType.CREWED_APOLLO,
            lat = -8.97301,
            lng = 15.50019,
            mission = LunarMissionMetadata("NASA", "US", "1972-04-21", 95.71, "LRV-002"),
            significance = "Only Apollo mission to land in the rugged central lunar highlands.",
        ),
        LunarLandmark(
            id = "apollo-17",
            name = "Apollo 17",
            latinName = "Taurus-Littrow Valley",
            type = LunarLandmarkType.CREWED_APOLLO,
            lat = 20.19080,
            lng = 30.77168,
            mission = LunarMissionMetadata("NASA", "US", "1972-12-11", 110.52, "LRV-003"),
            significance = "Final crewed Apollo mission featuring geologist Harrison Schmitt; discovered orange volcanic glass.",
        ),
        // Historic Soviet Luna (USSR)
        LunarLandmark(
            id = "luna-2",
            name = "Luna 2",
            latinName = "Palus Putredinis",
            type = LunarLandmarkType.HISTORIC_ROBOTIC,
            lat = 29.1,
            lng = 0.0,
            mission = LunarMissionMetadata("USSR", "RU", "1959-09-13", null, null),
            significance = "First human-made object to impact the Moon, confirming lack of a significant lunar magnetic field.",
        ),
        LunarLandmark(
            id = "luna-9",
            name = "Luna 9",
            latinName = "Oceanus Procellarum",
            type = LunarLandmarkType.HISTORIC_ROBOTIC,
            lat = 7.08,
            lng = -64.37,
            mission = LunarMissionMetadata("USSR", "RU", "1966-02-03", null, null),
            significance = "First successful soft landing on another celestial body, transmitting the first close-up lunar panoramas.",
        ),
        LunarLandmark(
            id = "luna-17",
            name = "Luna 17 (Lunokhod 1)",
            latinName = "Mare Imbrium",
            type = LunarLandmarkType.HISTORIC_ROBOTIC,
            lat = 38.28,
            lng = -35.0,
            mission = LunarMissionMetadata("USSR", "RU", "1970-11-17", null, "Lunokhod 1"),
            significance = "First remote-controlled robotic rover on another world, traveling over 10.5 km in 11 months.",
        ),
        LunarLandmark(
            id = "luna-24",
            name = "Luna 24",
            latinName = "Mare Crisium",
            type = LunarLandmarkType.HISTORIC_ROBOTIC,
            lat = 12.71,
            lng = 62.21,
            mission = LunarMissionMetadata("USSR", "RU", "1976-08-18", 0.17, null),
            significance = "Final Soviet robotic sample return mission, extracting a 2-meter core sample proving lunar water trace presence.",
        ),
        // Modern International Fleet (China, India, Japan)
        LunarLandmark(
            id = "change-3",
            name = "Chang'e 3 (Yutu)",
            latinName = "Mare Imbrium",
            type = LunarLandmarkType.MODERN_INTERNATIONAL,
            lat = 44.12,
            lng = -19.51,
            mission = LunarMissionMetadata("CNSA", "CN", "2013-12-14", null, "Yutu"),
            significance = "China's first soft lunar landing and Yutu rover deployment since 1976.",
        ),
        LunarLandmark(
            id = "change-4",
            name = "Chang'e 4 (Yutu-2)",
            latinName = "Von Kármán Crater",
            type = LunarLandmarkType.MODERN_INTERNATIONAL,
            lat = -45.45,
            lng = 177.60,
            mission = LunarMissionMetadata("CNSA", "CN", "2019-01-03", null, "Yutu-2"),
            significance = "First soft landing on the lunar far side inside the South Pole-Aitken Basin via Queqiao relay satellite.",
            isFarSide = true,
        ),
        LunarLandmark(
            id = "change-5",
            name = "Chang'e 5",
            latinName = "Oceanus Procellarum",
            type = LunarLandmarkType.MODERN_INTERNATIONAL,
            lat = 43.06,
            lng = -51.92,
            mission = LunarMissionMetadata("CNSA", "CN", "2020-12-01", 1.73, null),
            significance = "First lunar sample return in 44 years, collecting young 2.0 billion-year-old basaltic rock.",
        ),
        LunarLandmark(
            id = "change-6",
            name = "Chang'e 6",
            latinName = "Apollo Basin",
            type = LunarLandmarkType.MODERN_INTERNATIONAL,
            lat = -41.64,
            lng = -153.99,
            mission = LunarMissionMetadata("CNSA", "CN", "2024-06-01", 1.93, null),
            significance = "Historic first sample return from the lunar far side inside the giant South Pole-Aitken basin.",
            isFarSide = true,
        ),
        LunarLandmark(
            id = "chandrayaan-3",
            name = "Chandrayaan-3 (Vikram)",
            latinName = "Shiv Shakti Point",
            type = LunarLandmarkType.MODERN_INTERNATIONAL,
            lat = -69.37,
            lng = 32.35,
            mission = LunarMissionMetadata("ISRO", "IN", "2023-08-23", null, "Pragyan"),
            significance = "India's historic soft landing near the lunar south pole; Pragyan rover confirmed in-situ sulfur.",
        ),
        LunarLandmark(
            id = "slim",
            name = "SLIM (Smart Lander)",
            latinName = "Shioli Crater",
            type = LunarLandmarkType.MODERN_INTERNATIONAL,
            lat = -13.31,
            lng = 25.25,
            mission = LunarMissionMetadata("JAXA", "JP", "2024-01-19", null, "LEV-1 / LEV-2"),
            significance = "Japan's precision 'Moon Sniper' lander achieving unprecedented 55-meter landing accuracy.",
        ),
        // Commercial CLPS & Artemis South Pole
        LunarLandmark(
            id = "im-1",
            name = "IM-1 Odysseus",
            latinName = "Malapert A",
            type = LunarLandmarkType.COMMERCIAL_CLPS,
            lat = -80.13,
            lng = 1.44,
            mission = LunarMissionMetadata("Intuitive Machines", "US", "2024-02-22", null, null),
            significance = "First commercial U.S. lunar lander under NASA's CLPS program, landing 300 km from South Pole.",
        ),
        LunarLandmark(
            id = "artemis-3-shackleton",
            name = "Artemis III Candidate: Shackleton Rim",
            latinName = "Shackleton Crater",
            type = LunarLandmarkType.ARTEMIS_SOUTH_POLE,
            lat = -89.90,
            lng = 0.0,
            mission = LunarMissionMetadata("NASA / Artemis", "US", "Target 2026", null, null),
            significance = "Permanently Shadowed Region (PSR) harboring deep water ice deposits and continuous solar power peaks.",
        ),
    )
