package com.dirzaaulia.countries.domain.moon

val LUNAR_GEOLOGY_FORMATIONS: List<LunarLandmark> =
    listOf(
        // Lunar Maria (Basaltic Lava Plains)
        LunarLandmark(
            id = "mare-tranquillitatis",
            name = "Mare Tranquillitatis",
            latinName = "Sea of Tranquillity",
            type = LunarLandmarkType.LUNAR_MARE,
            lat = 8.5,
            lng = 31.4,
            diameterKm = 873.0,
            geologicPeriod = LunarGeologicPeriod.IMBRIAN,
            significance = "Ancient basaltic lava plain formed by 3.5-3.8 billion-year-old flood volcanism; site of Apollo 11.",
        ),
        LunarLandmark(
            id = "mare-imbrium",
            name = "Mare Imbrium",
            latinName = "Sea of Rains",
            type = LunarLandmarkType.LUNAR_MARE,
            lat = 32.8,
            lng = -15.6,
            diameterKm = 1145.0,
            geologicPeriod = LunarGeologicPeriod.IMBRIAN,
            significance = "Massive impact basin flooded by titanium-rich dark basaltic lava flows.",
        ),
        LunarLandmark(
            id = "oceanus-procellarum",
            name = "Oceanus Procellarum",
            latinName = "Ocean of Storms",
            type = LunarLandmarkType.LUNAR_MARE,
            lat = 18.4,
            lng = -57.4,
            diameterKm = 2568.0,
            geologicPeriod = LunarGeologicPeriod.IMBRIAN,
            significance = "Largest lunar maria plain, covering over 10% of the Moon's surface.",
        ),
        LunarLandmark(
            id = "mare-serenitatis",
            name = "Mare Serenitatis",
            latinName = "Sea of Serenity",
            type = LunarLandmarkType.LUNAR_MARE,
            lat = 28.0,
            lng = 17.5,
            diameterKm = 674.0,
            geologicPeriod = LunarGeologicPeriod.IMBRIAN,
            significance = "Circular mare basin featuring prominent wrinkle ridges and dark-mantle pyroclastic deposits.",
        ),
        LunarLandmark(
            id = "mare-crisium",
            name = "Mare Crisium",
            latinName = "Sea of Crises",
            type = LunarLandmarkType.LUNAR_MARE,
            lat = 17.0,
            lng = 59.1,
            diameterKm = 556.0,
            geologicPeriod = LunarGeologicPeriod.NECTARIAN,
            significance = "Isolated circular mare basin surrounded by a multi-ringed mountain wall.",
        ),

        // Prominent Impact Craters
        LunarLandmark(
            id = "tycho",
            name = "Tycho Crater",
            latinName = "Tycho",
            type = LunarLandmarkType.IMPACT_CRATER,
            lat = -43.31,
            lng = -11.36,
            diameterKm = 85.0,
            geologicPeriod = LunarGeologicPeriod.COPERNICAN,
            significance = "Young 108 million-year-old crater featuring the Moon's most prominent bright ray system extending over 1,500 km.",
        ),
        LunarLandmark(
            id = "copernicus",
            name = "Copernicus Crater",
            latinName = "Copernicus",
            type = LunarLandmarkType.IMPACT_CRATER,
            lat = 9.62,
            lng = -20.08,
            diameterKm = 93.0,
            geologicPeriod = LunarGeologicPeriod.COPERNICAN,
            significance = "Monumental crater with terraced walls 3.8 km deep and multiple central peaks.",
        ),
        LunarLandmark(
            id = "kepler",
            name = "Kepler Crater",
            latinName = "Kepler",
            type = LunarLandmarkType.IMPACT_CRATER,
            lat = 8.1,
            lng = -38.01,
            diameterKm = 31.0,
            geologicPeriod = LunarGeologicPeriod.COPERNICAN,
            significance = "Bright rayed crater situated between Oceanus Procellarum and Mare Insularum.",
        ),
        LunarLandmark(
            id = "aristarchus",
            name = "Aristarchus Crater",
            latinName = "Aristarchus",
            type = LunarLandmarkType.IMPACT_CRATER,
            lat = 23.7,
            lng = -47.4,
            diameterKm = 40.0,
            geologicPeriod = LunarGeologicPeriod.COPERNICAN,
            significance = "Brightest formation on the Moon, exceeding twice the albedo of average lunar surface features.",
        ),
        LunarLandmark(
            id = "south-pole-aitken",
            name = "South Pole-Aitken Basin",
            latinName = "Basin Aitken",
            type = LunarLandmarkType.IMPACT_CRATER,
            lat = -53.0,
            lng = 169.0,
            diameterKm = 2500.0,
            geologicPeriod = LunarGeologicPeriod.PRE_NECTARIAN,
            significance = "Largest and oldest impact basin in the Solar System, exposing deep lunar mantle materials.",
            isFarSide = true,
        ),
    )

val ALL_LUNAR_LANDMARKS: List<LunarLandmark> = LUNAR_HERITAGE_MISSIONS + LUNAR_GEOLOGY_FORMATIONS
